### ISSUE TITLE
Need more than 50 videos on UploadParser

### ISSUE THREAD

**Issue by rostirolla** [rebus007/YouTubeHelper#1]
Hey, thanks for the great lib. Real time saver! My only problem is that I need to get more than 50 videos on UploadParser, but if I put anything greater than 50 on setNumber() it won't accept.
Is there any way to have more than 50 on UploadParser or with any other object?

Thanks!

**Comment by raphaelbussa** [comment]
Unfortunately YouTube api return at most 50 results. Sorry.
